// <auto-generated />
namespace rendevusistemi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class delemploies_ıd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(delemploies_ıd));
        
        string IMigrationMetadata.Id
        {
            get { return "201803282022327_delemploies_ıd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
